"""
slx-runner: Run pll_stability_9bus.slx via matlab -batch and extract signals.

Usage:
    from runner import run_simulation
    data = run_simulation(signals=['ang_pll', 'p_inv', 'q_inv'])
    # data['t'] = time vector, data['ang_pll'] = numpy array, ...
"""

import subprocess, os, json, tempfile
import scipy.io, numpy as np
from pathlib import Path

PROJECT_ROOT = Path(__file__).parents[3]
SKILL_DIR    = Path(__file__).parent
SIGNAL_MAP   = json.loads((SKILL_DIR / 'signal_map.json').read_text())

_MATLAB_TEMPLATE = r"""
% Auto-generated by slx-runner skill — do not edit manually
model    = 'pll_stability_9bus';
out_file = '{out_file}';
cd('{project_root}');

load_system(model);
run('params.m');

% --- signal map: name -> scope SID + port index ---
{signal_map_block}

% --- enable DataLogging via port handles (non-destructive) ---
logged = {{}};
for k = 1:size(signal_cfg, 1)
    sig_name  = signal_cfg{{k,1}};
    scope_sid = signal_cfg{{k,2}};
    port_idx  = signal_cfg{{k,3}};
    scope_blk = find_by_sid(model, scope_sid);
    if isempty(scope_blk), warning('SID %s not found', scope_sid); continue; end
    ph     = get_param(scope_blk, 'PortHandles');
    if port_idx > numel(ph.Inport), continue; end
    line_h = get_param(ph.Inport(port_idx), 'Line');
    if line_h <= 0, continue; end
    src_ph = get_param(line_h, 'SrcPortHandle');
    set_param(src_ph, 'DataLogging', 'on', 'DataLoggingName', sig_name);
    logged{{end+1}} = sig_name;
end

% --- simulate ---
simout = sim(model);

% --- extract and save ---
results = struct('t', []);
if ~isempty(simout.logsout)
    for k = 1:numel(logged)
        try
            ts = simout.logsout.getElement(logged{{k}});
            if isempty(results.t), results.t = ts.Values.Time; end
            results.(logged{{k}}) = ts.Values.Data;
        catch ex
            warning('Could not extract %s: %s', logged{{k}}, ex.message);
        end
    end
end
save(out_file, '-struct', 'results');
close_system(model, 0);
fprintf('slx-runner: saved %d signals to %s\n', numel(logged), out_file);

function path = find_by_sid(mdl, sid)
    blks = find_system(mdl, 'FindAll', 'on', 'type', 'block', 'SID', sid);
    if isempty(blks), path = ''; else, path = getfullname(blks(1)); end
end
"""

def _build_signal_cfg(selected):
    rows = []
    for name in selected:
        if name not in SIGNAL_MAP:
            raise ValueError(f"Signal '{name}' not in signal_map.json")
        e = SIGNAL_MAP[name]
        rows.append(f"    {{'{name}', '{e['scope_sid']}', {e['port']}}}")
    body = ';\n'.join(rows) + ';'
    return f"signal_cfg = {{\n{body}\n}};"

def run_simulation(signals=None, out_file=None, timeout=300):
    """
    Run the Simulink model and return extracted signal data.

    Parameters
    ----------
    signals  : list[str] | None — keys from signal_map.json. None = all signals.
    out_file : str | None       — path for the .mat output. Defaults to project root.
    timeout  : int              — MATLAB subprocess timeout in seconds.

    Returns
    -------
    dict  {signal_name: np.ndarray, 't': np.ndarray}
    """
    if signals is None:
        signals = list(SIGNAL_MAP.keys())
    if out_file is None:
        out_file = str(PROJECT_ROOT / 'sim_results.mat')

    script = _MATLAB_TEMPLATE.format(
        out_file=out_file.replace('\\', '/'),
        project_root=str(PROJECT_ROOT).replace('\\', '/'),
        signal_map_block=_build_signal_cfg(signals),
    )

    with tempfile.NamedTemporaryFile(mode='w', suffix='.m', delete=False,
                                     dir=PROJECT_ROOT, prefix='_slxrun_',
                                     encoding='utf-8') as f:
        f.write(script)
        script_path = f.name

    try:
        result = subprocess.run(
            ['matlab', '-batch', f"run('{script_path.replace(chr(92), '/')}')"],
            capture_output=True, text=True, timeout=timeout,
            cwd=str(PROJECT_ROOT),
        )
        if result.stdout:
            print(result.stdout)
        if result.returncode != 0:
            raise RuntimeError(f"MATLAB failed (code {result.returncode}):\n"
                               f"{result.stderr}\n{result.stdout}")
    finally:
        os.unlink(script_path)

    raw = scipy.io.loadmat(out_file, squeeze_me=True)
    return {k: v for k, v in raw.items() if not k.startswith('__')}


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Run Simulink model and extract signals')
    parser.add_argument('--signals', help='Comma-separated signal names (default: all)')
    parser.add_argument('--out',     help='Output .mat path')
    args = parser.parse_args()

    sigs = args.signals.split(',') if args.signals else None
    data = run_simulation(signals=sigs, out_file=args.out)
    print("Signals loaded:", [k for k in data if k != 't'])
    if 't' in data:
        t = np.asarray(data['t'])
        print(f"Time vector: {t[0]:.4f}s → {t[-1]:.4f}s  ({len(t)} samples)")
